#lang racket
(provide (all-defined-out))
(require "utils.rkt"
         (only-in "prop.rkt"
                  distrib remove-trivial
                  simpdnf simpcnf dpll))
;<term> ::= <var> | (<func> <term>*)
;<predicate> ::= (<pred> <term>*)
;<exp> ::= <bool>
;       |  <predicate>
;       |  (not <exp>)
;       |  (and <exp> <exp>)
;       |  (or <exp> <exp>)
;       |  (=> <exp> <exp>)
;       |  (<=> <exp> <exp>)
;       |  (forall <var> <exp>)
;       |  (exists <var> <exp>)
(struct interp (domain func pred))
(define (funcval m f)
  ((interp-func m) f))
(define (predval m p)
  ((interp-pred m) p))
(define ((termval m v) term)
  (match term
    (,x (guard (symbol? x)) (v x))
    ((,func . ,term*)
     (apply (funcval m func)
            (map (termval m v) term*)))))
(define (holds? m v exp)
  (match exp
    (,b (guard (boolean? b)) b)
    ((not ,e) (not (holds? m v e)))
    ((and ,e1 ,e2) (and (holds? m v e1)
                        (holds? m v e2)))
    ((or ,e1 ,e2) (or (holds? m v e1)
                      (holds? m v e2)))
    ((=> ,e1 ,e2) (or (not (holds? m v e1))
                      (holds? m v e2)))
    ((<=> ,e1 ,e2) (eq? (holds? m v e1)
                        (holds? m v e2)))
    ((forall ,x ,e)
     (forall? (lambda (a)
                (holds? m (extend v x a) e))
              (interp-domain m)))
    ((exists ,x ,e)
     (exists? (lambda (a)
                (holds? m (extend v x a) e))
              (interp-domain m)))
    ((,pred . ,term*)
     (apply (predval m pred)
            (map (termval m v) term*)))))
(define (fvt term)
  (match term
    (,x (guard (symbol? x)) (list x))
    ((,func . ,term*)
     (apply U* (map fvt term*)))))
(define (fv exp)
  (match exp
    (,b (guard (boolean? b)) '())
    ((not ,e) (fv e))
    ((,op ,e1 ,e2)
     (guard (connective2? op))
     (U (fv e1) (fv e2)))
    ((,q ,x ,e)
     (guard (quantifier? q))
     (D (fv e) (list x)))
    ((,pred . ,term*)
     (apply U* (map fvt term*)))))
(define (generalize exp)
  (Forall (fv exp) exp))
(define ((tsubst i) term)
  (match term
    (,x (guard (symbol? x)) (i x))
    ((,func . ,term*)
     `(,func . ,(map (tsubst i) term*)))))
(define (subst i exp)
  (match exp
    (,b (guard (boolean? b)) b)
    ((not ,e) `(not ,(subst i e)))
    ((,op ,e1 ,e2)
     (guard (connective2? op))
     `(,op ,(subst i e1) ,(subst i e2)))
    ((,q ,x ,e)
     (guard (quantifier? q))
     (qsubst i q x e))
    ((,pred . ,term*)
     `(,pred . ,(map (tsubst i) term*)))))
#;
(define (qsubst i q x e)
  (define x^ (gensym x))
  `(,q ,x^ ,(subst (extend i x x^) e)))
#;
(define (qsubst i q x e)
  (define (capture?)
    (exists?
     (lambda (y)
       (memq x (fvt (i y))))
     (D (fv e) (list x))))
  (define x^
    (if (capture?)
        (gensym x)
        x))
  `(,q ,x^ ,(subst (extend i x x^) e)))
(define (qsubst i q x e)
  (define (capture?)
    (exists?
     (lambda (y)
       (memq x (fvt (i y))))
     (D (fv e) (list x))))
  (define x^
    (if (capture?)
        (variant x (fv (subst (undefine i x) e)))
        x))
  `(,q ,x^ ,(subst (extend i x x^) e)))
(define (Quant q x e)
  (if (memq x (fv e))
      `(,q ,x ,e)
      e))
(define (simplify exp)
  (define (simp exp)
    (match exp
      ((not ,e1) (Not (simp e1)))
      ((and ,e1 ,e2) (And (simp e1) (simp e2)))
      ((or ,e1 ,e2) (Or (simp e1) (simp e2)))
      ((=> ,e1 ,e2) (Imp (simp e1) (simp e2)))
      ((<=> ,e1 ,e2) (Iff (simp e1) (simp e2)))
      ((,q ,x ,e)
       (guard (quantifier? q))
       (Quant q x (simp e)))
      (,else exp)))
  (simp exp))
(define (nnf exp)
  (define (Not exp)
    (match exp
      ((not ,e1) (nnf e1))
      ((and ,e1 ,e2)
       `(or ,(Not e1) ,(Not e2)))
      ((or ,e1 ,e2)
       `(and ,(Not e1) ,(Not e2)))
      ((=> ,e1 ,e2)
       `(and ,(nnf e1) ,(Not e2)))
      ((<=> ,e1 ,e2)
       `(or (and ,(nnf e1) ,(Not e2))
            (and ,(Not e1) ,(nnf e2))))
      ((forall ,x ,e)
       `(exists ,x ,(Not e)))
      ((exists ,x ,e)
       `(forall ,x ,(Not e)))
      (,else `(not ,exp))))
  (define (nnf exp)
    (match exp
      ((not ,e1) (Not e1))
      ((and ,e1 ,e2) `(and ,(nnf e1) ,(nnf e2)))
      ((or ,e1 ,e2) `(or ,(nnf e1) ,(nnf e2)))
      ((=> ,e1 ,e2) `(or ,(Not e1) ,(nnf e2)))
      ((<=> ,e1 ,e2)
       `(or (and ,(nnf e1) ,(nnf e2))
            (and ,(Not e1) ,(Not e2))))
      ((forall ,x ,e) `(forall ,x ,(nnf e)))
      ((exists ,x ,e) `(exists ,x ,(nnf e)))
      (,else exp)))
  (nnf (simplify exp)))
(define (pullquants exp)
  (define (rename flag x z e)
    (if (and flag (not (eq? x z)))
        (subst (\|=> x z) e)
        e))
  (define (pullq lf rf exp quant op x y p q)
    (define z (variant x (fv exp)))
    (define p^ (rename lf x z p))
    (define q^ (rename rf y z q))
    `(,quant ,z ,(pullquants `(,op ,p^ ,q^))))
  (define (pullquants exp)
    (match exp
      ((and (forall ,x ,p) (forall ,y ,q))
       (pullq #t #t exp 'forall 'and x y p q))
      ((or (exists ,x ,p) (exists ,y ,q))
       (pullq #t #t exp 'exists 'or x y p q))
      ((,op (,quant ,x ,p) ,q)
       (guard (quantifier? quant))
       (pullq #t #f exp quant op x x p q))
      ((,op ,p (,quant ,y ,q))
       (guard (quantifier? quant))
       (pullq #f #t exp quant op y y p q))
      (,else exp)))
  (pullquants exp))
(define (prenex exp)
  (match exp
    ((,q ,x ,e)
     (guard (quantifier? q))
     `(,q ,x ,(prenex e)))
    ((,op ,p ,q)
     (guard (memq op '(and or)))
     (pullquants `(,op ,(prenex p) ,(prenex q))))
    (,else exp)))
(define (pnf exp)
  (prenex (nnf exp)))
(define (funcs term)
  (match term
    (,var (guard (symbol? var)) '())
    ((,func . ,term*)
     (set-cons (list func (length term*))
               (funcs* term*)))))
(define (funcs* term*)
  (apply U* (map funcs term*)))
(define (functions exp)
  (match exp
    (,b (guard (boolean? b)) '())
    ((not ,e) (functions e))
    ((,op ,e1 ,e2)
     (guard (connective2? op))
     (U (functions e1) (functions e2)))
    ((,q ,x ,e)
     (guard (quantifier? q))
     (functions e))
    ((,pred . ,term*) (funcs* term*))))
(define (predicates exp)
  (match exp
    (,b (guard (boolean? b)) '())
    ((not ,e) (predicates e))
    ((,op ,e1 ,e2)
     (guard (connective2? op))
     (U (predicates e1) (predicates e2)))
    ((,q ,x ,e)
     (guard (quantifier? q))
     (predicates e))
    ((,pred . ,term*)
     (list (list pred (length term*))))))
(define (function-congruence f n)
  (if (= n 0)
      '()
      (let* ((x* (map (make-index 'x) (range n)))
             (y* (map (make-index 'y) (range n)))
             (ant (make-conj
                   (map (lambda (x y) `(= ,x ,y))
                        x* y*)))
             (con `(= (,f . ,x*) (,f . ,y*))))
        (list (Forall (append x* y*)
                      `(=> ,ant ,con))))))
(define (predicate-congruence p n)
  (if (= n 0)
      '()
      (let* ((x* (map (make-index 'x) (range n)))
             (y* (map (make-index 'y) (range n)))
             (ant (make-conj
                   (map (lambda (x y) `(= ,x ,y))
                        x* y*)))
             (con `(=> (,p . ,x*) (,p . ,y*))))
        (list (Forall (append x* y*)
                      `(=> ,ant ,con))))))
(define equivalence-axioms
  '((forall x (= x x))
    (forall
     x (forall
        y (forall
           z (=> (and (= x y) (= x z))
                 (= y z)))))))
(define (equalitize exp)
  (define allpreds (predicates exp))
  (if (member (list '= 2) allpreds)
      (let* ((axioms (append
                      (append-map
                       (curry apply function-congruence)
                       (functions exp))
                      (append-map
                       (curry apply predicate-congruence)
                       (remove (list '= 2) allpreds))
                      equivalence-axioms)))
        `(=> ,(make-conj axioms) ,exp))
      exp))
(define (specialize exp)
  (match exp
    ((forall ,x ,e) (specialize e))
    (,else exp)))
(define (askolemize exp)
  (define (skolem exp f*)
    (match exp
      ((exists ,y ,p)
       (define x* (fv exp))
       (define f
         (variant (if (null? x*)
                      (symbol-append 'c_ y)
                      (symbol-append 'f_ y))
                  f*))
       (skolem (subst (\|=> y (cons f x*)) p)
               (cons f f*)))
      ((forall ,x ,p)
       (let-values (((p f*) (skolem p f*)))
         (values `(forall ,x ,p) f*)))
      ((,op ,p ,q)
       (guard (memq op '(and or)))
       (skolem2 op p q f*))
      (,else (values exp f*))))
  (define (skolem2 op p q f*)
    (let*-values (((p f*) (skolem p f*))
                  ((q f*) (skolem q f*)))
      (values `(,op ,p ,q) f*)))
  (let-values (((exp f*)
                (skolem (nnf exp)
                        (image car (functions exp)))))
    exp))
(define (skolemize exp)
  (specialize (prenex (askolemize exp))))
(define (ev e v)
  (match e
    (,b (guard (boolean? b)) b)
    ((not ,e1) (not (ev e1 v)))
    ((and ,e1 ,e2) (and (ev e1 v) (ev e2 v)))
    ((or ,e1 ,e2) (or (ev e1 v) (ev e2 v)))
    ((=> ,e1 ,e2) (or (not (ev e1 v)) (ev e2 v)))
    ((<=> ,e1 ,e2) (eq? (ev e1 v) (ev e2 v)))
    ((,q ,x ,e)
     (guard (quantifier? q))
     (error 'ev "ev only accepts quantifier-free formulas"))
    ((,pred . ,term*) (v e))))
(define (pholds? d e) (ev e d))
(define (herbfuns exp)
  (let-values (((c* f*)
                (partition
                 (lambda (p)
                   (= (cadr p) 0))
                 (functions exp))))
    (if (null? c*)
        (values (list (list 'c 0)) f*)
        (values c* f*))))
(define (groundterms ct* f* n)
  (if (= n 0)
      ct*
      (append-map
       (lambda (p)
         (define f (car p))
         (define m (cadr p))
         (map (curry cons f)
              (groundtuples ct* f* (- n 1) m)))
       f*)))
(define (groundtuples ct* f* n m)
  (if (= m 0)
      (if (= n 0) '(()) '())
      (append-map
       (lambda (k)
         (allpairs
          cons
          (groundterms ct* f* k)
          (groundtuples ct* f* (- n k) (- m 1))))
       (range (+ n 1)))))
(define ((herbloop modify test pre post init) exp)
  (define exp0 (pre exp))
  (define v* (fv exp0))
  (define-values (c* f*)
    (herbfuns exp0))
  (define ct*
    (map (lambda (p) (list (car p))) c*))
  (define template (post exp0))
  (let loop ((current init) (n 0) (tried* '()) (tuple* '()))
    (if (null? tuple*)
        (loop current (+ n 1) tried*
              (groundtuples ct* f* n (length v*)))
        (let* ((tuple (car tuple*))
               (tuple* (cdr tuple*))
               (tried* (cons tuple tried*)))
          (define new
            (modify template
                    (curry subst (fpf v* tuple))
                    current))
          (printf "~s ground instances tried; ~s items in list\n"
                  (length tried*) (length new))
          (if (not (test new))
              tried*
              (loop new n tried* tuple*))))))
(define (SNG exp)
  (skolemize (Not (generalize exp))))
(define (gilmore_modify template instantiate current)
  (remove-trivial
   (distrib (image (curry image instantiate) template)
            current)))
(define gilmore
  (compose length
           (herbloop gilmore_modify (compose not null?)
                     SNG simpdnf '(()))))
(define (dp_modify template instantiate current)
  (U (image (curry image instantiate) template)
     current))
(define davis-putnam
  (compose length (herbloop dp_modify dpll SNG simpcnf '())))
(define e0
  (Imp (Forall '(x y)
               (Exists '(z) (Forall '(w) (Imp (And '(P x) '(Q y))
                                              (And '(R z) '(U w))))))
       (Imp (Exists '(x y) (And '(P x) '(Q y)))
            (Exists '(z) '(R z)))))
