#lang racket
(provide (all-defined-out))
(require "utils.rkt")
;<exp> ::= <bool>
;       |  <var>
;       |  (not <exp>)
;       |  (and <exp> <exp>)
;       |  (or <exp> <exp>)
;       |  (=> <exp> <exp>)
;       |  (<=> <exp> <exp>)
(define (ev e v)
  (match e
    (,b (guard (boolean? b)) b)
    (,x (guard (symbol? x)) (v x))
    ((not ,e1) (not (ev e1 v)))
    ((and ,e1 ,e2) (and (ev e1 v) (ev e2 v)))
    ((or ,e1 ,e2) (or (ev e1 v) (ev e2 v)))
    ((=> ,e1 ,e2) (or (not (ev e1 v)) (ev e2 v)))
    ((<=> ,e1 ,e2) (eq? (ev e1 v) (ev e2 v)))))
(define (onAtoms f e)
  (match e
    (,b (guard (boolean? b)) b)
    (,x (guard (symbol? x)) (f x))
    ((not ,e1) `(not ,(onAtoms f e1)))
    ((,op ,e1 ,e2)
     `(,op ,(onAtoms f e1)
           ,(onAtoms f e2)))))
(define (atoms e)
  (match e
    (,b (guard (boolean? b)) '())
    (,x (guard (symbol? x)) (list x))
    ((not ,e1) (atoms e1))
    ((,op ,e1 ,e2) (U (atoms e1) (atoms e2)))))
(define (allv f v a*)
  (if (null? a*)
      (f v)
      (let ((a (car a*))
            (a* (cdr a*)))
        (define ((v^ b) x)
          (if (eq? x a) b (v x)))
        (and (allv f (v^ #f) a*)
             (allv f (v^ #t) a*)))))
(define (tautology? e)
  (allv (curry ev e)
        (lambda (x) #f)
        (atoms e)))
(define (unsatisfiable? e)
  (tautology? `(not ,e)))
(define (satisfiable? e)
  (not (unsatisfiable? e)))
(define (psubst f p)
  (onAtoms f p))
(define (psimplify exp)
  (define (simp exp)
    (match exp
      ((not ,e1) (Not (simp e1)))
      ((and ,e1 ,e2) (And (simp e1) (simp e2)))
      ((or ,e1 ,e2) (Or (simp e1) (simp e2)))
      ((=> ,e1 ,e2) (Imp (simp e1) (simp e2)))
      ((<=> ,e1 ,e2) (Iff (simp e1) (simp e2)))
      (,else exp)))
  (simp exp))
;<nnf> ::= <bool> | <nnf0>
;<nnf0> ::= <literal>
;        |  (and <nnf0> <nnf0>)
;        |  (or <nnf0> <nnf0>)
;<literal> ::= <var> | (not <var>)
(define (nnf exp)
  (define (Not exp)
    (match exp
      ((not ,e1) (nnf e1))
      ((and ,e1 ,e2)
       `(or ,(Not e1) ,(Not e2)))
      ((or ,e1 ,e2)
       `(and ,(Not e1) ,(Not e2)))
      ((=> ,e1 ,e2)
       `(and ,(nnf e1) ,(Not e2)))
      ((<=> ,e1 ,e2)
       `(or (and ,(nnf e1) ,(Not e2))
            (and ,(Not e1) ,(nnf e2))))
      (,else `(not ,exp))))
  (define (nnf exp)
    (match exp
      ((not ,e1) (Not e1))
      ((and ,e1 ,e2) `(and ,(nnf e1) ,(nnf e2)))
      ((or ,e1 ,e2) `(or ,(nnf e1) ,(nnf e2)))
      ((=> ,e1 ,e2) `(or ,(Not e1) ,(nnf e2)))
      ((<=> ,e1 ,e2)
       `(or (and ,(nnf e1) ,(nnf e2))
            (and ,(Not e1) ,(Not e2))))
      (,else exp)))
  (nnf (psimplify exp)))
(define (nnf? exp)
  (define (? exp)
    (match exp
      (,x (guard (symbol? x)) #t)
      ((not ,e1) (if (symbol? e1) #t #f))
      ((and ,e1 ,e2) (and (? e1) (? e2)))
      ((or ,e1 ,e2) (and (? e1) (? e2)))
      (,else #f)))
  (if (boolean? exp)
      #t
      (? exp)))
(define ((make-lits x*) v)
  (make-conj
   (map (lambda (x)
          (if (v x) x `(not ,x)))
        x*)))
(define (allsat f v a*)
  (if (null? a*)
      (if (f v) (list v) '())
      (let ((a (car a*))
            (a* (cdr a*)))
        (define ((v^ b) x)
          (if (eq? x a) b (v x)))
        (append (allsat f (v^ #f) a*)
                (allsat f (v^ #t) a*)))))
#;
(define (dnf exp)
  (let* ((a* (atoms exp))
         (v* (allsat (curry ev exp)
                     (lambda (x) #f)
                     a*)))
    (make-disj
     (map (make-lits a*) v*))))
;<dnf> ::= <bool> | <dnf0>
;<dnf0> ::= <conj> | (or <dnf0> <dnf0>)
;<conj> ::= <literal> | (and <conj> <conj>)
;<literal> ::= <var> | (not <var>)
(define (negative? literal)
  (and (pair? literal)
       (eq? (car literal) 'not)))
(define (positive? literal)
  (not (negative? literal)))
(define (negate literal)
  (match literal
    ((not ,atom) atom)
    (,else `(not ,literal))))
(define (trivial? lits)
  (let-values (((p n) (partition positive? lits)))
    (I? p (map negate n))))
(define (remove-trivial clauses)
  (filter (compose not trivial?) clauses))
(define (subsume exp)
  (let rec ((rest (sort (remove-trivial exp)
                        > #:key length)))
    (cond ((null? rest) '())
          ((memf (lambda (d)
                   (subset? d (car rest)))
                 (cdr rest))
           (rec (cdr rest)))
          (else (cons (car rest)
                      (rec (cdr rest)))))))
(define (distrib s1 s2)
  (setlize (allpairs U s1 s2)))
(define (purednf0 exp)
  (define (dnf exp)
    (match exp
      ((and ,e1 ,e2)
       (distrib (dnf e1) (dnf e2)))
      ((or ,e1 ,e2)
       (U (dnf e1) (dnf e2)))
      (,else `((,exp)))))
  (cond ((eq? exp #f) '())
        ((eq? exp #t) '(()))
        (else (dnf exp))))
(define purednf
  (compose purednf0 nnf))
(define (simpdnf exp)
  (subsume (purednf exp)))
(define (make-dnf lst)
  (make-disj (map make-conj lst)))
(define (dnf exp)
  (make-dnf (simpdnf exp)))
(define (purecnf exp)
  (map (curry map negate)
       (purednf `(not ,exp))))
(define (simpcnf exp)
  (subsume (purecnf exp)))
(define (make-cnf lst)
  (make-conj (map make-disj lst)))
(define (cnf exp)
  (make-cnf (simpcnf exp)))
(define (nenf exp)
  (define (Not exp)
    (match exp
      ((not ,e1) (nenf e1))
      ((and ,e1 ,e2)
       `(or ,(Not e1) ,(Not e2)))
      ((or ,e1 ,e2)
       `(and ,(Not e1) ,(Not e2)))
      ((=> ,e1 ,e2)
       `(and ,(nenf e1) ,(Not e2)))
      ((<=> ,e1 ,e2)
       `(<=> ,(nenf e1) ,(Not e2)))
      (,else `(not ,exp))))
  (define (nenf exp)
    (match exp
      ((not ,e1) (Not e1))
      ((and ,e1 ,e2) `(and ,(nenf e1) ,(nenf e2)))
      ((or ,e1 ,e2) `(or ,(nenf e1) ,(nenf e2)))
      ((=> ,e1 ,e2) `(or ,(Not e1) ,(nenf e2)))
      ((<=> ,e1 ,e2)
       `(<=> ,(nenf e1) ,(nenf e2)))
      (,else exp)))
  (nenf (psimplify exp)))
#;
(define (tseitin exp)
  (define (tseitin exp d*)
    (match exp
      ((,op ,e1 ,e2)
       (let*-values (((l1 d*) (tseitin e1 d*))
                     ((l2 d*) (tseitin e2 d*)))
         (let ((x (fresh-var))
               (e `(,op ,l1 ,l2)))
           (values x (cons `(<=> ,x ,e) d*)))))
      (,else (values exp d*))))
  (tseitin (nenf exp) '()))
#;
(define (tseitin exp)
  (define (lookup e d*)
    (match d*
      (((<=> ,x ,p) . ,d*)
       (if (equal? e p)
           x
           (lookup e d*)))
      (,else #f)))
  (define (tseitin exp d*)
    (match exp
      ((,op ,e1 ,e2)
       (let*-values (((l1 d*) (tseitin e1 d*))
                     ((l2 d*) (tseitin e2 d*)))
         (define e `(,op ,l1 ,l2))
         (define x (lookup e d*))
         (if x
             (values x d*)
             (let ((x (fresh-var)))
               (values x (cons `(<=> ,x ,e) d*))))))
      (,else (values exp d*))))
  (tseitin (nenf exp) '()))
;<cnf> ::= <bool> | <cnf0>
;<cnf0> ::= <disj> | (and <cnf0> <cnf0>)
;<disj> ::= <literal> | (or <disj> <disj>)
(define (tseitin exp)
  (define (lookup e d*)
    (match d*
      (((<=> ,x ,p) . ,d*)
       (if (equal? e p)
           x
           (lookup e d*)))
      (,else #f)))
  (define (Exp step op e1 e2 d*)
    (let*-values (((e1 d*) (step e1 d*))
                  ((e2 d*) (step e2 d*)))
      (values `(,op ,e1 ,e2) d*)))
  (define (CNF exp d*)
    (match exp
      ((and ,e1 ,e2) (Exp CNF 'and e1 e2 d*))
      (,else (Conjunct exp d*))))
  (define (Conjunct exp d*)
    (match exp
      ((or ,e1 ,e2) (Exp Conjunct 'or e1 e2 d*))
      (,else (Literal exp d*))))
  (define (Literal exp d*)
    (match exp
      ((,op ,e1 ,e2)
       (let-values (((e d*) (Exp Literal op e1 e2 d*)))
         (define x (lookup e d*))
         (if x
             (values x d*)
             (let ((x (fresh-var)))
               (values x (cons `(<=> ,x ,e) d*))))))
      (,else (values exp d*))))
  (CNF (nenf exp) '()))
(define (defcnf exp)
  (let-values (((p d*) (tseitin exp)))
    (append-map simpcnf (cons p d*))))
(define (one-literal-rule clauses)
  (define lit
    (let ((m (memf (lambda (clause)
                     (if (null? clause)
                         #f
                         (null? (cdr clause))))
                   clauses)))
      (and m (caar m))))
  (and lit
       (map (curry remove (negate lit))
            (filter (lambda (clause)
                      (not (member lit clause)))
                    clauses))))
(define (affirmative-negative-rule clauses)
  (let-values (((neg^ pos) (partition negative? (apply U* clauses))))
    (define neg (image negate neg^))
    (define pos_only (D pos neg))
    (define neg_only (D neg pos))
    (define pure
      (U pos_only (map negate neg_only)))
    (if (null? pure)
        #f
        (filter (lambda (clause)
                  (not (I? pure clause)))
                clauses))))
;(affirmative-negative-rule '((p (not r)) (p r) (q r) ((not q) r)))
(define (resolve-on p clauses)
  (define -p (negate p))
  (define-values (pos notpos)
    (partition (curry member p) clauses))
  (define-values (neg other)
    (partition (curry member -p) notpos))
  (define C*
    (map (curry filter (lambda (l)
                         (not (equal? l p))))
         pos))
  (define D*
    (map (curry filter (lambda (l)
                         (not (equal? l -p))))
         neg))
  (define res0 (allpairs U C* D*))
  (U other (remove-trivial res0)))
;(resolve-on 'p '((p (not q)) ((not p) q) (q)))
(define ((resolution-blowup clauses) literal)
  (define m
    (length
     (filter (curry member literal) clauses)))
  (define n
    (length
     (filter (curry member (negate literal)) clauses)))
  (- (* m n) m n))
(define (resolution-rule clauses)
  (define p*
    (filter positive? (apply U* clauses)))
  (define p
    (minimize (resolution-blowup clauses) p*))
  (resolve-on p clauses))
(define (dp clauses)
  (cond ((null? clauses) #t)
        ((member '() clauses) #f)
        (else
         (let ((new (one-literal-rule clauses)))
           (if new (dp new)
               (let ((new (affirmative-negative-rule clauses)))
                 (if new (dp new)
                     (dp (resolution-rule clauses)))))))))
(define (dpsat? exp)
  (dp (defcnf exp)))
(define (dptaut? exp)
  (not (dpsat? `(not ,exp))))
(define ((posneg-count clauses) literal)
  (define m
    (length
     (filter (curry member literal) clauses)))
  (define n
    (length
     (filter (curry member (negate literal)) clauses)))
  (+ m n))
(define (dpll clauses)
  (cond ((null? clauses) #t)
        ((member '() clauses) #f)
        (else
         (let ((new (one-literal-rule clauses)))
           (if new (dpll new)
               (let ((new (affirmative-negative-rule clauses)))
                 (if new (dpll new)
                     (splitting-rule clauses))))))))
(define (splitting-rule clauses)
  (define p*
    (filter positive? (apply U* clauses)))
  (define p
    (maximize (posneg-count clauses) p*))
  (or (dpll (cons (list p) clauses))
      (dpll (cons (list (negate p)) clauses))))
(define (dpllsat? exp)
  (dpll (defcnf exp)))
(define (dplltaut? exp)
  (not (dpllsat? `(not ,exp))))
