#lang racket
(require "utils.rkt" "fol.rkt")
(define (empty-env) '())
(define (extend-env x v env)
  (cons (cons x v) env))
(define (defined? env x)
  (if (assq x env) #t #f))
(define (apply-env env x)
  (cond ((assq x env) => cdr)
        (else
         (error 'apply-env "unbound var ~s" x))))
(define (trivial? env x t)
  (match t
    (,y
     (guard (symbol? y))
     (or (eq? y x)
         (and (defined? env y)
              (trivial? env x (apply-env env y)))))
    ((,f . ,arg*)
     (and (exists? (curry trivial? env x) arg*)
          (error 'trivial? "cyclic")))))
(define (unify env eq*)
  (define (unify env eq*)
    (if (null? eq*)
        env
        (match eq*
          ((((,f . ,a*) . (,g . ,b*)) . ,eq*)
           (if (and (eq? f g)
                    (= (length a*) (length b*)))
               (unify env (append (map cons a* b*) eq*))
               (error 'unify "impossible unification")))
          (((,x . ,t) . ,eq*)
           (guard (symbol? x))
           (u env x t eq*))
          (((,t . ,x) . ,eq*)
           (guard (symbol? x))
           (u env x t eq*)))))
  (define (u env x t eq*)
    (if (defined? env x)
        (unify env `((,(apply-env env x) . ,t) . ,eq*))
        (unify (if (trivial? env x t)
                   env
                   (extend-env x t env))
               eq*)))
  (unify env eq*))
